
//package pt.lsts.neptus.plugins.groovy.scripts
import pt.lsts.neptus.nvl.imc.dsl.*


// Plan builder
def plan = new Plan ("Plan-From-Groovy")

plan.with {
    


def home = new Location(41.185242, -8.704803)

locate home 


speed.units = Speed.Units.METERS_PS
speed.value = 1.2


z.value = 5
z.units = Z.Units.ALTITUDE

def new_z = new Z(3,Z.Units.DEPTH)

goTo id:"xpto",z:new_z


move 100, 0


z.value = 4


loiter duration:240


z.value = 0
z.units = Z.Units.DEPTH


skeeping location:home



description = "This is a PlanSpecification generated by a Groovy builder"

addToConsole(console) //from binding


}





