// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trex.proto

package org.mbari.trex;

public final class Trex {
  private Trex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PredicateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string object = 1;
    boolean hasObject();
    String getObject();
    
    // required string predicate = 2;
    boolean hasPredicate();
    String getPredicate();
    
    // required fixed64 start = 3;
    boolean hasStart();
    long getStart();
    
    // repeated .org.mbari.trex.Predicate.Variable attributes = 4;
    java.util.List<org.mbari.trex.Trex.Predicate.Variable> 
        getAttributesList();
    org.mbari.trex.Trex.Predicate.Variable getAttributes(int index);
    int getAttributesCount();
    java.util.List<? extends org.mbari.trex.Trex.Predicate.VariableOrBuilder> 
        getAttributesOrBuilderList();
    org.mbari.trex.Trex.Predicate.VariableOrBuilder getAttributesOrBuilder(
        int index);
  }
  public static final class Predicate extends
      com.google.protobuf.GeneratedMessage
      implements PredicateOrBuilder {
    // Use Predicate.newBuilder() to construct.
    private Predicate(Builder builder) {
      super(builder);
    }
    private Predicate(boolean noInit) {}
    
    private static final Predicate defaultInstance;
    public static Predicate getDefaultInstance() {
      return defaultInstance;
    }
    
    public Predicate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_fieldAccessorTable;
    }
    
    public interface FloatDomainOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional double min_v = 1;
      boolean hasMinV();
      double getMinV();
      
      // optional double max_v = 2;
      boolean hasMaxV();
      double getMaxV();
    }
    public static final class FloatDomain extends
        com.google.protobuf.GeneratedMessage
        implements FloatDomainOrBuilder {
      // Use FloatDomain.newBuilder() to construct.
      private FloatDomain(Builder builder) {
        super(builder);
      }
      private FloatDomain(boolean noInit) {}
      
      private static final FloatDomain defaultInstance;
      public static FloatDomain getDefaultInstance() {
        return defaultInstance;
      }
      
      public FloatDomain getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_FloatDomain_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_FloatDomain_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional double min_v = 1;
      public static final int MIN_V_FIELD_NUMBER = 1;
      private double minV_;
      public boolean hasMinV() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getMinV() {
        return minV_;
      }
      
      // optional double max_v = 2;
      public static final int MAX_V_FIELD_NUMBER = 2;
      private double maxV_;
      public boolean hasMaxV() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getMaxV() {
        return maxV_;
      }
      
      private void initFields() {
        minV_ = 0D;
        maxV_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, minV_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, maxV_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, minV_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, maxV_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.FloatDomain parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.mbari.trex.Trex.Predicate.FloatDomain prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_FloatDomain_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_FloatDomain_fieldAccessorTable;
        }
        
        // Construct using org.mbari.trex.Trex.Predicate.FloatDomain.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          minV_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          maxV_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.mbari.trex.Trex.Predicate.FloatDomain.getDescriptor();
        }
        
        public org.mbari.trex.Trex.Predicate.FloatDomain getDefaultInstanceForType() {
          return org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance();
        }
        
        public org.mbari.trex.Trex.Predicate.FloatDomain build() {
          org.mbari.trex.Trex.Predicate.FloatDomain result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.mbari.trex.Trex.Predicate.FloatDomain buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.mbari.trex.Trex.Predicate.FloatDomain result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.mbari.trex.Trex.Predicate.FloatDomain buildPartial() {
          org.mbari.trex.Trex.Predicate.FloatDomain result = new org.mbari.trex.Trex.Predicate.FloatDomain(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.minV_ = minV_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.maxV_ = maxV_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.mbari.trex.Trex.Predicate.FloatDomain) {
            return mergeFrom((org.mbari.trex.Trex.Predicate.FloatDomain)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.mbari.trex.Trex.Predicate.FloatDomain other) {
          if (other == org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance()) return this;
          if (other.hasMinV()) {
            setMinV(other.getMinV());
          }
          if (other.hasMaxV()) {
            setMaxV(other.getMaxV());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                minV_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                maxV_ = input.readDouble();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional double min_v = 1;
        private double minV_ ;
        public boolean hasMinV() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public double getMinV() {
          return minV_;
        }
        public Builder setMinV(double value) {
          bitField0_ |= 0x00000001;
          minV_ = value;
          onChanged();
          return this;
        }
        public Builder clearMinV() {
          bitField0_ = (bitField0_ & ~0x00000001);
          minV_ = 0D;
          onChanged();
          return this;
        }
        
        // optional double max_v = 2;
        private double maxV_ ;
        public boolean hasMaxV() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public double getMaxV() {
          return maxV_;
        }
        public Builder setMaxV(double value) {
          bitField0_ |= 0x00000002;
          maxV_ = value;
          onChanged();
          return this;
        }
        public Builder clearMaxV() {
          bitField0_ = (bitField0_ & ~0x00000002);
          maxV_ = 0D;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:org.mbari.trex.Predicate.FloatDomain)
      }
      
      static {
        defaultInstance = new FloatDomain(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.mbari.trex.Predicate.FloatDomain)
    }
    
    public interface VariableOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string name = 1;
      boolean hasName();
      String getName();
      
      // optional .org.mbari.trex.Predicate.FloatDomain int_d = 2;
      boolean hasIntD();
      org.mbari.trex.Trex.Predicate.FloatDomain getIntD();
      org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder getIntDOrBuilder();
      
      // optional bool bool_d = 3;
      boolean hasBoolD();
      boolean getBoolD();
      
      // repeated string enum_d = 4;
      java.util.List<String> getEnumDList();
      int getEnumDCount();
      String getEnumD(int index);
    }
    public static final class Variable extends
        com.google.protobuf.GeneratedMessage
        implements VariableOrBuilder {
      // Use Variable.newBuilder() to construct.
      private Variable(Builder builder) {
        super(builder);
      }
      private Variable(boolean noInit) {}
      
      private static final Variable defaultInstance;
      public static Variable getDefaultInstance() {
        return defaultInstance;
      }
      
      public Variable getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_Variable_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_Variable_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional .org.mbari.trex.Predicate.FloatDomain int_d = 2;
      public static final int INT_D_FIELD_NUMBER = 2;
      private org.mbari.trex.Trex.Predicate.FloatDomain intD_;
      public boolean hasIntD() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.mbari.trex.Trex.Predicate.FloatDomain getIntD() {
        return intD_;
      }
      public org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder getIntDOrBuilder() {
        return intD_;
      }
      
      // optional bool bool_d = 3;
      public static final int BOOL_D_FIELD_NUMBER = 3;
      private boolean boolD_;
      public boolean hasBoolD() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getBoolD() {
        return boolD_;
      }
      
      // repeated string enum_d = 4;
      public static final int ENUM_D_FIELD_NUMBER = 4;
      private com.google.protobuf.LazyStringList enumD_;
      public java.util.List<String>
          getEnumDList() {
        return enumD_;
      }
      public int getEnumDCount() {
        return enumD_.size();
      }
      public String getEnumD(int index) {
        return enumD_.get(index);
      }
      
      private void initFields() {
        name_ = "";
        intD_ = org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance();
        boolD_ = false;
        enumD_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, intD_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBool(3, boolD_);
        }
        for (int i = 0; i < enumD_.size(); i++) {
          output.writeBytes(4, enumD_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, intD_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, boolD_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < enumD_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(enumD_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getEnumDList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.mbari.trex.Trex.Predicate.Variable parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.mbari.trex.Trex.Predicate.Variable prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.mbari.trex.Trex.Predicate.VariableOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_Variable_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_Variable_fieldAccessorTable;
        }
        
        // Construct using org.mbari.trex.Trex.Predicate.Variable.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getIntDFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (intDBuilder_ == null) {
            intD_ = org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance();
          } else {
            intDBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          boolD_ = false;
          bitField0_ = (bitField0_ & ~0x00000004);
          enumD_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.mbari.trex.Trex.Predicate.Variable.getDescriptor();
        }
        
        public org.mbari.trex.Trex.Predicate.Variable getDefaultInstanceForType() {
          return org.mbari.trex.Trex.Predicate.Variable.getDefaultInstance();
        }
        
        public org.mbari.trex.Trex.Predicate.Variable build() {
          org.mbari.trex.Trex.Predicate.Variable result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.mbari.trex.Trex.Predicate.Variable buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.mbari.trex.Trex.Predicate.Variable result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.mbari.trex.Trex.Predicate.Variable buildPartial() {
          org.mbari.trex.Trex.Predicate.Variable result = new org.mbari.trex.Trex.Predicate.Variable(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (intDBuilder_ == null) {
            result.intD_ = intD_;
          } else {
            result.intD_ = intDBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.boolD_ = boolD_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            enumD_ = new com.google.protobuf.UnmodifiableLazyStringList(
                enumD_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.enumD_ = enumD_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.mbari.trex.Trex.Predicate.Variable) {
            return mergeFrom((org.mbari.trex.Trex.Predicate.Variable)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.mbari.trex.Trex.Predicate.Variable other) {
          if (other == org.mbari.trex.Trex.Predicate.Variable.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasIntD()) {
            mergeIntD(other.getIntD());
          }
          if (other.hasBoolD()) {
            setBoolD(other.getBoolD());
          }
          if (!other.enumD_.isEmpty()) {
            if (enumD_.isEmpty()) {
              enumD_ = other.enumD_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureEnumDIsMutable();
              enumD_.addAll(other.enumD_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                org.mbari.trex.Trex.Predicate.FloatDomain.Builder subBuilder = org.mbari.trex.Trex.Predicate.FloatDomain.newBuilder();
                if (hasIntD()) {
                  subBuilder.mergeFrom(getIntD());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setIntD(subBuilder.buildPartial());
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                boolD_ = input.readBool();
                break;
              }
              case 34: {
                ensureEnumDIsMutable();
                enumD_.add(input.readBytes());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // optional .org.mbari.trex.Predicate.FloatDomain int_d = 2;
        private org.mbari.trex.Trex.Predicate.FloatDomain intD_ = org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            org.mbari.trex.Trex.Predicate.FloatDomain, org.mbari.trex.Trex.Predicate.FloatDomain.Builder, org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder> intDBuilder_;
        public boolean hasIntD() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public org.mbari.trex.Trex.Predicate.FloatDomain getIntD() {
          if (intDBuilder_ == null) {
            return intD_;
          } else {
            return intDBuilder_.getMessage();
          }
        }
        public Builder setIntD(org.mbari.trex.Trex.Predicate.FloatDomain value) {
          if (intDBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            intD_ = value;
            onChanged();
          } else {
            intDBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder setIntD(
            org.mbari.trex.Trex.Predicate.FloatDomain.Builder builderForValue) {
          if (intDBuilder_ == null) {
            intD_ = builderForValue.build();
            onChanged();
          } else {
            intDBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder mergeIntD(org.mbari.trex.Trex.Predicate.FloatDomain value) {
          if (intDBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                intD_ != org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance()) {
              intD_ =
                org.mbari.trex.Trex.Predicate.FloatDomain.newBuilder(intD_).mergeFrom(value).buildPartial();
            } else {
              intD_ = value;
            }
            onChanged();
          } else {
            intDBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder clearIntD() {
          if (intDBuilder_ == null) {
            intD_ = org.mbari.trex.Trex.Predicate.FloatDomain.getDefaultInstance();
            onChanged();
          } else {
            intDBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        public org.mbari.trex.Trex.Predicate.FloatDomain.Builder getIntDBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getIntDFieldBuilder().getBuilder();
        }
        public org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder getIntDOrBuilder() {
          if (intDBuilder_ != null) {
            return intDBuilder_.getMessageOrBuilder();
          } else {
            return intD_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            org.mbari.trex.Trex.Predicate.FloatDomain, org.mbari.trex.Trex.Predicate.FloatDomain.Builder, org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder> 
            getIntDFieldBuilder() {
          if (intDBuilder_ == null) {
            intDBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                org.mbari.trex.Trex.Predicate.FloatDomain, org.mbari.trex.Trex.Predicate.FloatDomain.Builder, org.mbari.trex.Trex.Predicate.FloatDomainOrBuilder>(
                    intD_,
                    getParentForChildren(),
                    isClean());
            intD_ = null;
          }
          return intDBuilder_;
        }
        
        // optional bool bool_d = 3;
        private boolean boolD_ ;
        public boolean hasBoolD() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public boolean getBoolD() {
          return boolD_;
        }
        public Builder setBoolD(boolean value) {
          bitField0_ |= 0x00000004;
          boolD_ = value;
          onChanged();
          return this;
        }
        public Builder clearBoolD() {
          bitField0_ = (bitField0_ & ~0x00000004);
          boolD_ = false;
          onChanged();
          return this;
        }
        
        // repeated string enum_d = 4;
        private com.google.protobuf.LazyStringList enumD_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureEnumDIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            enumD_ = new com.google.protobuf.LazyStringArrayList(enumD_);
            bitField0_ |= 0x00000008;
           }
        }
        public java.util.List<String>
            getEnumDList() {
          return java.util.Collections.unmodifiableList(enumD_);
        }
        public int getEnumDCount() {
          return enumD_.size();
        }
        public String getEnumD(int index) {
          return enumD_.get(index);
        }
        public Builder setEnumD(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureEnumDIsMutable();
          enumD_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addEnumD(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureEnumDIsMutable();
          enumD_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllEnumD(
            java.lang.Iterable<String> values) {
          ensureEnumDIsMutable();
          super.addAll(values, enumD_);
          onChanged();
          return this;
        }
        public Builder clearEnumD() {
          enumD_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        void addEnumD(com.google.protobuf.ByteString value) {
          ensureEnumDIsMutable();
          enumD_.add(value);
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:org.mbari.trex.Predicate.Variable)
      }
      
      static {
        defaultInstance = new Variable(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.mbari.trex.Predicate.Variable)
    }
    
    private int bitField0_;
    // required string object = 1;
    public static final int OBJECT_FIELD_NUMBER = 1;
    private java.lang.Object object_;
    public boolean hasObject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getObject() {
      java.lang.Object ref = object_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          object_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getObjectBytes() {
      java.lang.Object ref = object_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        object_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string predicate = 2;
    public static final int PREDICATE_FIELD_NUMBER = 2;
    private java.lang.Object predicate_;
    public boolean hasPredicate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPredicate() {
      java.lang.Object ref = predicate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          predicate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPredicateBytes() {
      java.lang.Object ref = predicate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        predicate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required fixed64 start = 3;
    public static final int START_FIELD_NUMBER = 3;
    private long start_;
    public boolean hasStart() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getStart() {
      return start_;
    }
    
    // repeated .org.mbari.trex.Predicate.Variable attributes = 4;
    public static final int ATTRIBUTES_FIELD_NUMBER = 4;
    private java.util.List<org.mbari.trex.Trex.Predicate.Variable> attributes_;
    public java.util.List<org.mbari.trex.Trex.Predicate.Variable> getAttributesList() {
      return attributes_;
    }
    public java.util.List<? extends org.mbari.trex.Trex.Predicate.VariableOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    public int getAttributesCount() {
      return attributes_.size();
    }
    public org.mbari.trex.Trex.Predicate.Variable getAttributes(int index) {
      return attributes_.get(index);
    }
    public org.mbari.trex.Trex.Predicate.VariableOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }
    
    private void initFields() {
      object_ = "";
      predicate_ = "";
      start_ = 0L;
      attributes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasObject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPredicate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAttributesCount(); i++) {
        if (!getAttributes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getObjectBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPredicateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, start_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(4, attributes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getObjectBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPredicateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, start_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, attributes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.mbari.trex.Trex.Predicate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.mbari.trex.Trex.Predicate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.mbari.trex.Trex.Predicate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.mbari.trex.Trex.Predicate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.mbari.trex.Trex.PredicateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mbari.trex.Trex.internal_static_org_mbari_trex_Predicate_fieldAccessorTable;
      }
      
      // Construct using org.mbari.trex.Trex.Predicate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        object_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        predicate_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        start_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mbari.trex.Trex.Predicate.getDescriptor();
      }
      
      public org.mbari.trex.Trex.Predicate getDefaultInstanceForType() {
        return org.mbari.trex.Trex.Predicate.getDefaultInstance();
      }
      
      public org.mbari.trex.Trex.Predicate build() {
        org.mbari.trex.Trex.Predicate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.mbari.trex.Trex.Predicate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.mbari.trex.Trex.Predicate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.mbari.trex.Trex.Predicate buildPartial() {
        org.mbari.trex.Trex.Predicate result = new org.mbari.trex.Trex.Predicate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.object_ = object_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.predicate_ = predicate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.start_ = start_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mbari.trex.Trex.Predicate) {
          return mergeFrom((org.mbari.trex.Trex.Predicate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.mbari.trex.Trex.Predicate other) {
        if (other == org.mbari.trex.Trex.Predicate.getDefaultInstance()) return this;
        if (other.hasObject()) {
          setObject(other.getObject());
        }
        if (other.hasPredicate()) {
          setPredicate(other.getPredicate());
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000008);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasObject()) {
          
          return false;
        }
        if (!hasPredicate()) {
          
          return false;
        }
        if (!hasStart()) {
          
          return false;
        }
        for (int i = 0; i < getAttributesCount(); i++) {
          if (!getAttributes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              object_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              predicate_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              start_ = input.readFixed64();
              break;
            }
            case 34: {
              org.mbari.trex.Trex.Predicate.Variable.Builder subBuilder = org.mbari.trex.Trex.Predicate.Variable.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttributes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string object = 1;
      private java.lang.Object object_ = "";
      public boolean hasObject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getObject() {
        java.lang.Object ref = object_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          object_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setObject(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        object_ = value;
        onChanged();
        return this;
      }
      public Builder clearObject() {
        bitField0_ = (bitField0_ & ~0x00000001);
        object_ = getDefaultInstance().getObject();
        onChanged();
        return this;
      }
      void setObject(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        object_ = value;
        onChanged();
      }
      
      // required string predicate = 2;
      private java.lang.Object predicate_ = "";
      public boolean hasPredicate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPredicate() {
        java.lang.Object ref = predicate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          predicate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPredicate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        predicate_ = value;
        onChanged();
        return this;
      }
      public Builder clearPredicate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        predicate_ = getDefaultInstance().getPredicate();
        onChanged();
        return this;
      }
      void setPredicate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        predicate_ = value;
        onChanged();
      }
      
      // required fixed64 start = 3;
      private long start_ ;
      public boolean hasStart() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getStart() {
        return start_;
      }
      public Builder setStart(long value) {
        bitField0_ |= 0x00000004;
        start_ = value;
        onChanged();
        return this;
      }
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000004);
        start_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .org.mbari.trex.Predicate.Variable attributes = 4;
      private java.util.List<org.mbari.trex.Trex.Predicate.Variable> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          attributes_ = new java.util.ArrayList<org.mbari.trex.Trex.Predicate.Variable>(attributes_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.mbari.trex.Trex.Predicate.Variable, org.mbari.trex.Trex.Predicate.Variable.Builder, org.mbari.trex.Trex.Predicate.VariableOrBuilder> attributesBuilder_;
      
      public java.util.List<org.mbari.trex.Trex.Predicate.Variable> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      public org.mbari.trex.Trex.Predicate.Variable getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      public Builder setAttributes(
          int index, org.mbari.trex.Trex.Predicate.Variable value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAttributes(
          int index, org.mbari.trex.Trex.Predicate.Variable.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAttributes(org.mbari.trex.Trex.Predicate.Variable value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAttributes(
          int index, org.mbari.trex.Trex.Predicate.Variable value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAttributes(
          org.mbari.trex.Trex.Predicate.Variable.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAttributes(
          int index, org.mbari.trex.Trex.Predicate.Variable.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAttributes(
          java.lang.Iterable<? extends org.mbari.trex.Trex.Predicate.Variable> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          super.addAll(values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      public org.mbari.trex.Trex.Predicate.Variable.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      public org.mbari.trex.Trex.Predicate.VariableOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.mbari.trex.Trex.Predicate.VariableOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      public org.mbari.trex.Trex.Predicate.Variable.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            org.mbari.trex.Trex.Predicate.Variable.getDefaultInstance());
      }
      public org.mbari.trex.Trex.Predicate.Variable.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, org.mbari.trex.Trex.Predicate.Variable.getDefaultInstance());
      }
      public java.util.List<org.mbari.trex.Trex.Predicate.Variable.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.mbari.trex.Trex.Predicate.Variable, org.mbari.trex.Trex.Predicate.Variable.Builder, org.mbari.trex.Trex.Predicate.VariableOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.mbari.trex.Trex.Predicate.Variable, org.mbari.trex.Trex.Predicate.Variable.Builder, org.mbari.trex.Trex.Predicate.VariableOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.mbari.trex.Predicate)
    }
    
    static {
      defaultInstance = new Predicate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.mbari.trex.Predicate)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mbari_trex_Predicate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mbari_trex_Predicate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mbari_trex_Predicate_FloatDomain_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mbari_trex_Predicate_FloatDomain_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mbari_trex_Predicate_Variable_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mbari_trex_Predicate_Variable_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntrex.proto\022\016org.mbari.trex\"\222\002\n\tPredica" +
      "te\022\016\n\006object\030\001 \002(\t\022\021\n\tpredicate\030\002 \002(\t\022\r\n" +
      "\005start\030\003 \002(\006\0226\n\nattributes\030\004 \003(\0132\".org.m" +
      "bari.trex.Predicate.Variable\032+\n\013FloatDom" +
      "ain\022\r\n\005min_v\030\001 \001(\001\022\r\n\005max_v\030\002 \001(\001\032n\n\010Var" +
      "iable\022\014\n\004name\030\001 \002(\t\0224\n\005int_d\030\002 \001(\0132%.org" +
      ".mbari.trex.Predicate.FloatDomain\022\016\n\006boo" +
      "l_d\030\003 \001(\010\022\016\n\006enum_d\030\004 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_mbari_trex_Predicate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_mbari_trex_Predicate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_mbari_trex_Predicate_descriptor,
              new java.lang.String[] { "Object", "Predicate", "Start", "Attributes", },
              org.mbari.trex.Trex.Predicate.class,
              org.mbari.trex.Trex.Predicate.Builder.class);
          internal_static_org_mbari_trex_Predicate_FloatDomain_descriptor =
            internal_static_org_mbari_trex_Predicate_descriptor.getNestedTypes().get(0);
          internal_static_org_mbari_trex_Predicate_FloatDomain_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_mbari_trex_Predicate_FloatDomain_descriptor,
              new java.lang.String[] { "MinV", "MaxV", },
              org.mbari.trex.Trex.Predicate.FloatDomain.class,
              org.mbari.trex.Trex.Predicate.FloatDomain.Builder.class);
          internal_static_org_mbari_trex_Predicate_Variable_descriptor =
            internal_static_org_mbari_trex_Predicate_descriptor.getNestedTypes().get(1);
          internal_static_org_mbari_trex_Predicate_Variable_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_mbari_trex_Predicate_Variable_descriptor,
              new java.lang.String[] { "Name", "IntD", "BoolD", "EnumD", },
              org.mbari.trex.Trex.Predicate.Variable.class,
              org.mbari.trex.Trex.Predicate.Variable.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
