
package fr.cls.argos.dataxmldistribution.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import fr.cls.argos.dataxmldistribution.service.types.CsvRequestType;
import fr.cls.argos.dataxmldistribution.service.types.KmlRequestType;
import fr.cls.argos.dataxmldistribution.service.types.ObjectFactory;
import fr.cls.argos.dataxmldistribution.service.types.ObservationRequestType;
import fr.cls.argos.dataxmldistribution.service.types.PlatformListRequestType;
import fr.cls.argos.dataxmldistribution.service.types.StreamResponseType;
import fr.cls.argos.dataxmldistribution.service.types.StringResponseType;
import fr.cls.argos.dataxmldistribution.service.types.XmlRequestType;
import fr.cls.argos.dataxmldistribution.service.types.XsdRequestType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DixServicePortType", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DixServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get Argos data on CSV format")
    @WebResult(name = "csvResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getCsv(
        @WebParam(name = "csvRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        CsvRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StreamResponseType
     * @throws DixException
     */
    @WebMethod
    @WebResult(name = "streamXmlResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StreamResponseType getStreamXml(
        @WebParam(name = "streamXmlRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        XmlRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get Argos data on KML format")
    @WebResult(name = "kmlResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getKml(
        @WebParam(name = "kmlRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        KmlRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get Argos data on XML format")
    @WebResult(name = "xmlResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getXml(
        @WebParam(name = "xmlRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        XmlRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get the XSD for the XML format")
    @WebResult(name = "xsdResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getXsd(
        @WebParam(name = "xsdRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        XsdRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get the list of platforms")
    @WebResult(name = "platformListResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getPlatformList(
        @WebParam(name = "platformListRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        PlatformListRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get the observations on CSV Format")
    @WebResult(name = "observationResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getObsCsv(
        @WebParam(name = "observationRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        ObservationRequestType params)
        throws DixException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns fr.cls.argos.dataxmldistribution.service.types.StringResponseType
     * @throws DixException
     */
    @WebMethod(action = "Get the observations on XML Format")
    @WebResult(name = "observationResponse", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
    public StringResponseType getObsXml(
        @WebParam(name = "observationRequest", targetNamespace = "http://service.dataxmldistribution.argos.cls.fr/types", partName = "params")
        ObservationRequestType params)
        throws DixException
    ;

}
